[versions]
kotlin = "2.1.0"
clikt = "5.0.3"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version = "1.4.1" }
kotlin-clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }

doyaaaaaken-csv = { module = "com.github.doyaaaaaken:kotlin-csv-jvm", version = "1.2.0" }

[plugins]
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.7" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
